### ISSUE TITLE
Led lights have been added to indicate the status.

### ISSUE THREAD

**Issue by ahgitit** [ckcr4lyf/EvilAppleJuice-ESP32#10]
[EvilAppleJuice-ESP32-master_led_flash.zip](https://github.com/ckcr4lyf/EvilAppleJuice-ESP32/files/13198102/EvilAppleJuice-ESP32-master_led_flash.zip)

**Comment by ckcr4lyf** [comment]
Sorry, can you explain what this issue is about? I don't want to download an arbitrary zip file.

**Comment by ahgitit** [comment]
> Sorry, can you explain what this issue is about? I don't want to download an arbitrary zip file.

I made a new change, so that every time esp32 sends a signal, the leds will flash once.This allows us to intuitively know that he has carried out an attack.

**Comment by ckcr4lyf** [comment]
I can't do anything with just a zip file. Additionally I don't believe this adds to much value to the current scope of the project, since there is not guarantee that this had any effect on any iOS device.

You can surely use it in your own fork, and maybe link it here if you think it may help someone.

**Comment by ckcr4lyf** [comment]
Closing as no further comment.
